import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import useSWR from 'swr'
import dynamic from 'next/dynamic'

// import Books from '@/components/Books'
const Books = dynamic(() => import('@/components/Books'))

const fetcher = (url: URL) => fetch(url).then(res => res.json())

export default function Home() {

  const { data: books } = useSWR('https://63d8db905a330a6ae16f31da.mockapi.io/Books', fetcher)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Books books={books} />
      </main>
    </>
  )
}
